apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: nginx
spec:
  port: {{.Values.service.targetPort}}
  containers:
  - name: nginx
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - containerPort: {{.Values.service.targetPort}}