apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    resource: {{ .Values.resource.type }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: http
  selector:
    app: nginx